---
swagger: "2.0.0"
info:
  description: "Workgroup assistant microservice in Researcher Hub"
  version: "1.1.0"
  title: "Workgroup Assistant API"
security:
- defaultApiKey: []
paths:
  /load-signup:
    post:
      summary: "Load sign-up application payload as group member for new AI service\
        \ agent"
      operationId: "load_signupPOST"
      parameters:
      - name: "id"
        in: "header"
        required: true
        type: "integer"
        maximum: 5000000
        minimum: 0
        format: "int32"
      - name: "inviteremail"
        in: "header"
        required: false
        type: "string"
        format: "email"
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "The sign-up payload for workgroup members. The signup payload\
            \ is returned which includes avatar, name, email, password, slackname,\
            \ researchgate url, default app id, and default app description. A status\
            \ code 200 is returned.\n"
        "404":
          description: "No sign-up payload found for workgroup member. Error message\
            \ with  status code 404 is returned.\n"
        "500":
          description: "Internal error occured. Error message with status code  500\
            \ is returned.\n"
        "400":
          description: "Unexpected error occured. Error message with status code 400\
            \ is returned.\n"
      x-swagger-router-controller: "Default"
  /execute-signup:
    post:
      summary: "Commit a new sign-up application payload for group member with new\
        \ AI service agent onto Researcher Hub"
      operationId: "execute_signupPOST"
      parameters:
      - name: "avatar"
        in: "header"
        required: true
        type: "string"
        enum:
        - "robotPurple.png"
        - "robotGreen.png"
        - "robotOrange.png"
        - "robotRed.png"
      - name: "name"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "email"
        in: "header"
        required: true
        type: "string"
        format: "email"
      - name: "password"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "slackname"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "researchgate"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "defaultAppID"
        in: "header"
        required: true
        type: "string"
        maxLength: 500
      - name: "defaultAppDescription"
        in: "header"
        required: true
        type: "string"
        maxLength: 500
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "The credential of group member with existing AI service agent.\
            \ A standard OK message with  status code 200 is return.\n"
        "404":
          description: "No resource found for user credential. Error message with\
            \ status code  404 is returned.\n"
        "500":
          description: "Internal error occured. Error message with status code 500\
            \ is returned.\n"
        "400":
          description: "Unexpected error occured. Error message with status code \
            \ 400 is returned.\n"
      x-swagger-router-controller: "Default"
  /load-login:
    post:
      summary: "Load login payload as group member for existing AI service agent"
      operationId: "load_loginPOST"
      parameters:
      - name: "id"
        in: "header"
        required: true
        type: "integer"
        maximum: 5000000
        minimum: 0
        format: "int32"
      - name: "inviteremail"
        in: "header"
        required: false
        type: "string"
        format: "email"
      - name: "inviterDefaultAppId"
        in: "header"
        required: false
        type: "string"
        maxLength: 500
      - name: "inviterUserRole"
        in: "header"
        required: false
        type: "string"
        enum:
        - "Leader"
        - "Assistant"
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "The login payload for workgroup member. A login payload is\
            \ returned include with username and password. A status code 200 is also\
            \ returned.\n"
        "404":
          description: "No login payload found for workgroup member. Error message\
            \ with status code 404 is returned.\n"
        "500":
          description: "Internal error occured. Error message with status code 500\
            \ is returned.\n"
        "400":
          description: "Unexpected error occured. Error message with status code \
            \ 400 is returned.\n"
      x-swagger-router-controller: "Default"
  /execute-login:
    post:
      summary: "Submit a login with user credential payload for group member with\
        \ existing AI service agent"
      operationId: "execute_loginPOST"
      parameters:
      - name: "name"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "password"
        in: "header"
        required: true
        type: "string"
        maxLength: 256
      - name: "inviterDefaultAppId"
        in: "header"
        required: false
        type: "string"
        maxLength: 500
      - name: "inviterUserRole"
        in: "header"
        required: false
        type: "string"
        enum:
        - "Leader"
        - "Assistant"
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "The workgroup and member's profile on Researcher Hub. A standard\
            \ OK message is returned with a status code 200.\n"
        "404":
          description: "No resource found for workgroup and member's profile on Researcher\
            \ Hub. Error message is returned with status code 404.\n"
        "500":
          description: "Internal error occured. Error message is returned with status\
            \ code 500.\n"
        "400":
          description: "Unexpected error occured. Error message is returned with status\
            \ code 400.\n"
      x-swagger-router-controller: "Default"
  /load-workgroup:
    post:
      summary: "Get workgroup for AI service agent"
      operationId: "load_workgroupPOST"
      parameters:
      - name: "id"
        in: "header"
        required: true
        type: "integer"
        maximum: 5000000
        minimum: 0
        format: "int32"
      - name: "defaultAppID"
        in: "header"
        required: true
        type: "string"
        maxLength: 500
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "The workgroup payload for workgroup members. A workgroup payload\
            \ is returned  with list of group members, and conversation or chat history\
            \ of workgroup.\n"
        "404":
          description: "No resource found for workgroup on Researcher Hub. Error message\
            \ with status code 404 is returned.\n"
        "500":
          description: "Internal error occured. Error message with status code 500\
            \ is returned.\n"
        "400":
          description: "Unexpected error occured. Error message with status code 400\
            \ is returned.\n"
      x-swagger-router-controller: "Default"
  /load-members-profile:
    post:
      summary: "Get member's profile and voting preferences of AI service agent"
      operationId: "load_members_profilePOST"
      parameters:
      - name: "id"
        in: "header"
        required: true
        type: "integer"
        maximum: 5000000
        minimum: 0
        format: "int32"
      security:
      - defaultApiKey: []
      responses:
        "200":
          description: "An individual member's payload. A workgroup member payload\
            \ is returned with name, email, slackname, researchgate, avatar, and default\
            \ app id.  A status code 200 is returned.\n"
        "404":
          description: "No resource found for individual member on Researcher Hub.\
            \ Error message with status code 404 is returned.\n"
        "500":
          description: "Internal error occured. Error message with status code 500\
            \ is returned.\n"
        "400":
          description: "Unexpected error occured. Error message with status code 400\
            \ is returned.\n"
      x-swagger-router-controller: "Default"
  /execute-logout:
    post:
      summary: "Load logout payload as group member for existing AI service agent"
      operationId: "execute_logoutPOST"
      parameters: []
      responses:
        "200":
          description: "Success message to logout from Researcher Hub. A standard\
            \ OK message  with a status code 200 is returned.\n"
        "404":
          description: "No HTTP resource found for user logout process from Researcher\
            \ Hub. Error message with status code 404 is returned.\n"
        "500":
          description: "Error for internal error during user logout process. Error\
            \ message is returned with status code 500.\n"
        "400":
          description: "Error for unexpected error during user logout process. Error\
            \ message is returned with status code 400.\n"
      x-swagger-router-controller: "Default"
definitions: {}
