# coding: utf-8

"""
    Workgroup Assistant API

    Workgroup assistant microservice in Researcher Hub  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute_login_post(self):
        """Test case for execute_login_post

        Submit a login with user credential payload for group member with existing AI service agent  # noqa: E501
        """
        pass

    def test_execute_logout_post(self):
        """Test case for execute_logout_post

        Load logout payload as group member for existing AI service agent  # noqa: E501
        """
        pass

    def test_execute_signup_post(self):
        """Test case for execute_signup_post

        Commit a new sign-up application payload for group member with new AI service agent onto Researcher Hub  # noqa: E501
        """
        pass

    def test_load_login_post(self):
        """Test case for load_login_post

        Load login payload as group member for existing AI service agent  # noqa: E501
        """
        pass

    def test_load_members_profile_post(self):
        """Test case for load_members_profile_post

        Get member's profile and voting preferences of AI service agent  # noqa: E501
        """
        pass

    def test_load_signup_post(self):
        """Test case for load_signup_post

        Load sign-up application payload as group member for new AI service agent  # noqa: E501
        """
        pass

    def test_load_workgroup_post(self):
        """Test case for load_workgroup_post

        Get workgroup for AI service agent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
