# coding: utf-8

# flake8: noqa

"""
    Workgroup Assistant API

    Workgroup assistant microservice in Researcher Hub  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from workgroup_assistant_api_client.api.default_api import DefaultApi

# import ApiClient
from workgroup_assistant_api_client.api_client import ApiClient
from workgroup_assistant_api_client.configuration import Configuration
# import models into sdk package
