# coding: utf-8

"""
    Workgroup Assistant API

    Workgroup assistant microservice in Researcher Hub  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "workgroup-assistant-api"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Workgroup Assistant API",
    author_email="",
    url="https://github.com/brenai-works/workgroup-platform-microservice",
    keywords=["Swagger", "Workgroup Assistant API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Workgroup assistant microservice in Researcher Hub  # noqa: E501
    """
)
